name: CHM4930
channels:
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - numpy<2.0.0
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - rdkit
  - jupyter
  - nbstripout
  - pytest
  - pytorch
  - pip
  - pip:
      - torch_geometric
      - deepchem
